services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PSQL_PORT}:${PSQL_PORT}"
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    build: ./server
    container_name: springboot-app
    restart: unless-stopped
    ports:
      - "${SPRING_BOOT_PORT}:${SPRING_BOOT_PORT}"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    env_file:
      - ./.env

  django:
    build: ./django-app
    container_name: django-app
    restart: unless-stopped
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      DJANGO_PORT: ${DJANGO_PORT}
    volumes:
      - ./django-app:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    env_file:
      - .env
