services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${PSQL_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    build: ./server
    container_name: springboot-app
    restart: unless-stopped
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      # SERVER_PORT: 8080
    env_file:
      - ./.env

  django:
    build: ./django-app
    container_name: django-app
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      DJANGO_PORT: 8000
    volumes:
      - ./django-app:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "${NGINX_PORT}:80"           # 컨테이너 포트는 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./flutter-web-build:/usr/share/nginx/html
    depends_on:
      - app
    env_file:
      - .env
