spring:
  application:
    name: hackathon

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.example.domain

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.tool.schema: debug

jwt:
  secret: 2097744f1cf41787b4d38f13bc25d514b880b454a3b59f52ae829f20ac1020295dfd3edc8b0ccd53abf3beb7af902cd27edbeabf2b322d0039d54935acacabd7
